<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <RootNamespace>App</RootNamespace>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Forms\MainForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="..\Shared\Util.vb">
      <Link>Common\Util.vb</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\dotnet\App.Contract\App.Contract.vbproj" />
  </ItemGroup>
</Project>
