<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Basic</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Module1.vb" />
    <Compile Include="Forms\OrderForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Forms\OrderForm.Designer.vb">
      <DependentUpon>OrderForm.vb</DependentUpon>
    </Compile>
    <Compile Include="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Forms\OrderForm.resx">
      <DependentUpon>OrderForm.vb</DependentUpon>
    </EmbeddedResource>
    <None Include="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Include="App.config" />
  </ItemGroup>
</Project>
