<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SdkBasic</RootNamespace>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Excluded\**" />
    <Compile Include="..\Shared\Helper.vb" Link="Shared\Helper.vb" />
    <Compile Include="Legacy\Explicit.vb" />
    <Compile Update="Forms\MainForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\MainForm.Designer.vb">
      <DependentUpon>MainForm.vb</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <ProjectReference Include="..\Other\Other.vbproj" />
  </ItemGroup>

</Project>
